### PR TITLE
fix(errors): Update deprecated error handling #5

### PR DESCRIPTION
**Pull request by Nabeelhassan**
Please see if this is the appropriate fix you desired.

### CODE REVIEW

**Comment by brendon1555** [comment]
Hi @Nabeelhassan, thanks for the pull request. This fixes the issue for one of the error cases. 
Could you implement this for all error handling?

**Comment by Nabeelhassan** [comment]
By for all you mean the secret:get command ?

**Comment by brendon1555** [comment]
I actually meant across all of the commands. Anywhere within the project that we catch an error.

**Comment by Nabeelhassan** [comment]
could you please run/review it ? I hope it is up to the mark.

**Comment by brendon1555** [comment]
Looks good. Thanks for this. 👍

**Comment by Nabeelhassan** [comment]
Thank you too. stay blessed.

**Pull request merged**
